rhythmbox: Autospec creation for update from version 3.4.6 to version 3.4.7
Alan Mortensen (1):
      Update Danish translation

Alexandre Franke (1):
      Update French translation

Anders Jonsson (3):
      Update Swedish translation
      Update Swedish translation
      Update Swedish translation

Andika Triwidada (1):
      Add Indonesian translation

Andre Klapper (1):
      docs: Update some of the screenshots

Asier Sarasua Garmendia (1):
      Update Basque translation

Balázs Úr (1):
      Update Hungarian translation

Bastien Nocera (5):
      data: Add main window screenshot
      data: Update appdata screenshot to an existing one
      data: Update URL after merge to main branch
      backends: Fix traceback in artsearch plugin
      build: Check that necessary files get updated on release

Calvin Walton (1):
      build: Use get_variable function instead of running pkg-config

Daniel Mustieles (1):
      Updated Spanish translation

Daniel Rusek (1):
      Update Czech translation

Enrico Nicoletto (1):
      Update Brazilian Portuguese translation

Fran Dieguez (1):
      Update Galician translation

Geoff Hill (4):
      Fix JSON parser leak in audioscrobbler plugin
      Fix Last.fm top tracks web request
      Fix Last.fm top artists web request
      Remove recommended artists from audioscrobbler

Goran Vidović (1):
      Update Croatian translation

Hugo Carvalho (1):
      Update Portuguese translation

Irénée THIRION (1):
      Update French translation

Jake Dane (1):
      desktop: Remove obsolete Bugzilla entries

Jeremy Bicha (1):
      tests: Allow running tests without installed gsettings schemas

Jonathan Matthew (19):
      pythonconsole: add debugpy support
      add a vimspector config
      remove party mode
      make man pages mandoc -Tlint clean
      podcast: try to deal with episodes with the same filename
      irc channel moved
      shell: handle files that parse as playlists, but aren't
      build: don't try to use latest libdmapsharing-4.0
      build: only build daap plugin if explicitly enabled
      ugh
      build: require glib 2.66 so we can use GUri
      build: use meson.project_build_root() rather than meson.build_root()
      build: check which version of libsoup grilo was built with
      xfade: correctly remove bus watch when stopping sink
      switch to libsoup 3
      remove libdmapsharing api compatibility
      tests: fix shutdown idle handler
      rhythmdb: don't take a ref for the library location sync timeout
      Rhythmbox 3.4.7

Jordi Mas (2):
      Update Catalan translation
      Update Catalan translation

Kukuh Syafaat (1):
      Update Indonesian translation

Martin (1):
      Update Slovenian translation

Muhammet Kara (1):
      Update Turkish translation

Olga Smirnova (1):
      Add Interlingue translation

Philipp Wolfer (7):
      listenbrainz: remove batch submission on queue activation
      listenbrainz: include audio duration in submissions
      listenbrainz: apply timeout for network requests
      listenbrainz: less frequent checks for queue submission, but increase number of items submitted per call
      listenbrainz: use LB defined fields for client and source info
      listenbrainz: close HTTPS connection after use
      listenbrainz: do not submit tracks without duration on first second

Piotr Drąg (1):
      Update Polish translation

Quentin PAGÈS (1):
      Update Occitan translation

Sabri Ünal (6):
      Update Turkish translation
      Update Turkish translation
      Update Turkish translation
      Update Turkish translation
      Update Turkish translation
      Update Turkish translation

Sergej A (3):
      Update Russian translation
      Update Russian translation
      Update Russian translation

Sveinn í Felli (2):
      Update Icelandic translation
      Update Icelandic translation

Yuri Chornoivan (3):
      Update Ukrainian translation
      Update Ukrainian translation
      Update Ukrainian translation

Zurab Kargareteli (1):
      Add Georgian translation

crvi (4):
      podcast: set have_selection flag to false during every subscribe action
      podcast: do not set metadata errors on download status if download is complete
      tests: suffix the appropriate gulong duration in query
      playlist-manager: use filename instead of "Unnamed Playlist" for playlists without a name

Мирослав Николић (1):
      Update Serbian translation

Overview of changes in Rhythmbox 3.4.7
======================================

* Bug fix release for 3.4
* Requires libsoup 3
* Party mode removed
* debugpy support for Python plugin debugging

Issues fixed:
1591 - 'Import playlist from file' does not retain playlist file name
1818 - ListenBrainz: Rhythmbox hangs when blocked by firewall
1824 - Listenbrainz: ResourceWarning: unclosed <ssl.SSLSocket>
1983 - podcast: Crashes with SIGSEGV during podcast subscribe
1992 - AttributeError: 'gi.repository.RB' object has no attribute 'gst_process_embedded_image'
1993 - test-widgets fails on arm64

(NEWS truncated at 15 lines)